apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-platform-config
  namespace: ai-platform
data:
  AIP_LOG_LEVEL: "DEBUG"
  AIP_ENVIRONMENT: "banking"
  AIP_OTEL_ENABLED: "false"
  AIP_OTEL_EXPORTER: "console"
  AIP_OTEL_ENDPOINT: "http://localhost:4317"
  AIP_KAIROS_MODEL: "gpt-4o-mini"
  AIP_CHROMA_PERSIST_DIR: "/app/data/chroma"
