apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-platform-api
  namespace: ai-platform
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ai-platform-api
          env:
            - name: AIP_DEBUG
              value: "true"
            - name: AIP_LOG_LEVEL
              value: "DEBUG"
            - name: AIP_ENVIRONMENT
              value: "banking"
